### ISSUE TITLE
Will not capture correctly in obs. and missing sprites

### ISSUE THREAD

**Issue by JusTheNerd** [adamsb0303/Shiny_Hunt_Tracker#2]
We're capturing a black box for transparent or nothing at all depending on what compatibility we use. also there are lots of sprites after 958 that are missing. great tool and really appreciated but i hate i can't actively use it. chroma-key is scuffed due to the colors vary so widely.

**Comment by adamsb0303** [comment]
Thanks for letting me know about the sprites. I finished them up about a week ago. You can download them at the google drive link in the release information, and I just pulled them into master.

After some testing and digging, I was able to replicate the black box issue, and I found that OBS added the ability to record transparent backgrounds in version 28.0.
With a Window Capture and Capture Method "Window 10 (1903 and up)" it seems to capture perfectly.
https://github.com/obsproject/obs-studio/pull/6414

Since it looks like the issue is a windows one, I am going to close the ticket. Thank you so much for the feedback!
